# Setup
title:               Songheony
tagline:             '취미용 블로그'
description:         '일본에서 석사를 진행하고 있는 학생이 이것저것 흔적을 남기기 위한 블로그입니다.'
url:                 https://songheony.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              송 헌
  url:               https://songheony.github.io
  email:             songheony@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
